<style>
    :root{--hd-primary:#5b3fd3;--hd-primary-dark:#4327b9;--hd-border:#e7e9f0;--hd-muted:#77809a;--hd-success:#36b765}
    body{background:var(--app-background,#f7f8fc)!important;color:#202840}
    .followup-page{max-width:1800px;margin:0 auto;padding:0 1rem 1.5rem!important;font-size:14px;font-weight:500}
    .followup-layout-row{--bs-gutter-x:1.25rem;row-gap:1rem;align-items:stretch}
    .followup-main-card{background:transparent!important;border:0!important;box-shadow:none!important;margin:0!important}
    .followup-main-card>.card-header{display:none}.followup-main-card>.card-body{padding:0!important;gap:1rem!important}
    #filter-tiket-form{display:none!important}
    .detail-top-row>.col-md-6:first-child{width:100%!important;max-width:100%;flex:0 0 100%}
    .detail-top-row>.col-md-6:nth-child(2){display:none!important}
    .detail-ticket-compact{width:100%;height:450px!important;min-height:450px!important;border-radius:15px;box-shadow:0 10px 28px rgba(20,29,54,.14)}
    .detail-ticket-compact .flip-card-inner{height:100%;min-height:450px!important}.detail-ticket-compact .flip-card-front>.card{border:0;background:transparent!important;box-shadow:none}
    .ticket-overview{min-height:450px;padding:1.35rem;border-radius:15px;color:#fff;background:var(--app-ticket-card,linear-gradient(145deg,#20285d 0%,#142039 100%));transition:background .2s ease}
    .ticket-overview__page-heading{margin:-.15rem 0 1.1rem;padding-bottom:1rem;border-bottom:1px solid rgba(255,255,255,.1)}.ticket-overview__page-heading h1{margin:0 0 .25rem;color:#fff;font-size:1.4rem;font-weight:800}.ticket-overview__page-heading p{margin:0;color:#c3cae0;font-size:.82rem;font-weight:600}
    .ticket-overview__header{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;margin-bottom:1.25rem}.ticket-overview__eyebrow{display:block;color:#c1c9e2;font-size:.74rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em;margin-bottom:.35rem}.ticket-overview h2{color:#fff;font-size:1.35rem;font-weight:800;margin:0}
    .ticket-overview__actions{display:flex;align-items:center;gap:.55rem}.ticket-history-button{display:inline-flex;align-items:center;gap:.4rem;padding:.38rem .65rem;border:1px solid rgba(255,255,255,.24);border-radius:7px;background:rgba(255,255,255,.08);color:#fff;font-size:.65rem;font-weight:700;text-transform:uppercase}.ticket-history-button:hover{background:#fff;color:var(--hd-primary)}
    .status-pill{display:inline-flex;padding:.38rem .65rem;border-radius:7px;background:#65708d;color:#fff;font-size:.68rem;font-weight:800;text-transform:uppercase}.status-pill--open,.status-pill--in_progress{background:var(--hd-success)}.status-pill--rejected{background:#ef4444}
    .ticket-overview__grid{display:grid;grid-template-columns:1.15fr 1.45fr 1.15fr 1fr .8fr;gap:1rem}.ticket-field span:not(.officer-name){display:block;color:#c1c9df;font-size:.75rem;font-weight:600;margin-bottom:.25rem}.ticket-field strong{display:block;color:#fff;font-size:.9rem;font-weight:700;line-height:1.5}.ticket-field--wide{margin-bottom:.58rem}.ticket-overview__divider{height:1px;margin:.9rem 0;background:rgba(255,255,255,.1)}.ticket-whatsapp{color:#48d67a;margin-left:.35rem}.officer-name{display:inline-block;margin:0 .3rem .2rem 0}.officer-name.is-complete{color:#69dd8e}.ticket-overview__hint{color:#adb7d3;font-size:.72rem;font-weight:600;margin-top:.8rem}
    .flip-card-back{padding:1.35rem!important;border:1px solid rgba(255,255,255,.14);border-radius:15px;background:var(--app-ticket-card,linear-gradient(145deg,#20285d 0%,#142039 100%))!important;color:#fff;box-shadow:0 8px 24px rgba(21,31,53,.08);font-size:.8rem!important;font-weight:500;line-height:1.5;overflow-y:auto;transition:background .2s ease}.flip-card-back h6,.flip-card-back strong{color:#fff!important}.flip-card-back .text-muted,.flip-card-back .small.text-muted{color:rgba(255,255,255,.68)!important}.flip-card-back a{color:#dcd6ff}
    #detail-tiket-card>.row+ .row,.followup-main-card>.card-body>.row.g-2.mb-3{row-gap:1rem!important;margin-bottom:0!important}
    #detail-tiket-card>.row+ .row>div,.followup-main-card>.card-body>.row.g-2.mb-3>div{display:flex;margin-bottom:0!important}
    #detail-tiket-card>.row+ .row .card,.followup-main-card>.card-body>.row.g-2.mb-3 .card{width:100%;height:100%!important;max-height:none!important;border:1px solid var(--hd-border);border-radius:15px;box-shadow:0 6px 22px rgba(26,33,56,.05);overflow:hidden}
    #detail-tiket-card>.row+ .row .card-header{min-height:68px;display:flex;align-items:center;padding:1.15rem 1.25rem;border-bottom:1px solid var(--hd-border);background:#fff}#detail-tiket-card>.row+ .row .card-header h6{color:#28356b;font-size:1rem;font-weight:700}
    .followup-role-action-card>.card-header{min-height:68px;display:flex;align-items:center;gap:.65rem;padding:1.15rem 1.25rem!important;border-bottom:1px solid var(--hd-border);background:#fff}.followup-role-action-card>.card-header h6{color:#28356b;font-size:1rem;font-weight:700}.role-action-icon{width:30px;height:30px;flex:0 0 auto;display:grid;place-items:center;border-radius:9px;background:#eeeaff;color:var(--hd-primary)}.role-action-icon svg{width:17px;height:17px;display:block}
    .followup-role-action-row{row-gap:1rem!important;margin-bottom:0!important}.followup-role-action-row>div{display:flex;margin-bottom:0!important}.followup-role-action-card{width:100%;height:100%!important;max-height:none!important;border:1px solid var(--hd-border);border-radius:15px;box-shadow:0 6px 22px rgba(26,33,56,.05);overflow:hidden}.followup-role-action-card>.card-body{padding:1rem 1.25rem!important}
    .officer-followup-form-row textarea{min-height:112px;resize:vertical}.officer-followup-side-column{min-height:112px}.officer-followup-side-column .btn{min-height:38px}
    #detail-tiket-card>.row+ .row .card-body,.followup-main-card>.card-body>.row.g-2.mb-3 .card-body{padding:1rem 1.25rem!important}.followup-main-card textarea,.followup-main-card .form-control,.followup-main-card .form-select{border-color:var(--hd-border);border-radius:9px;font-size:.84rem;font-weight:600;box-shadow:none}.followup-main-card textarea:focus,.followup-main-card .form-control:focus,.followup-main-card .form-select:focus{border-color:var(--hd-primary);box-shadow:0 0 0 3px rgba(91,63,211,.1)}
    #detail-tiket-card>.row+ .row .btn-outline-primary,.followup-main-card>.card-body>.row.g-2.mb-3 .btn-outline-primary{background:var(--hd-primary);border-color:var(--hd-primary);color:#fff}#detail-tiket-card>.row+ .row .btn-outline-success,.followup-main-card>.card-body>.row.g-2.mb-3 .btn-outline-success{background:var(--hd-success);border-color:var(--hd-success);color:#fff}
    .chat-ticket-summary,.followup-chat-card{border:1px solid var(--hd-border);border-radius:15px;background:#fff;box-shadow:0 6px 22px rgba(26,33,56,.05);overflow:hidden}.chat-ticket-summary__header,.followup-chat-card>.card-header{display:flex;align-items:center;justify-content:space-between;padding:.9rem 1rem!important;border-bottom:1px solid var(--hd-border);background:#fff}.chat-ticket-summary__eyebrow{display:block;color:var(--hd-primary);font-size:.66rem;font-weight:800;text-transform:uppercase}.chat-ticket-summary__header h6,.followup-chat-card>.card-header h6{margin:0;color:#28356b;font-size:.95rem;font-weight:700}.chat-ticket-summary__body{max-height:285px;padding:.75rem;overflow-y:auto}.qa-panel,.closing-panel{border:0!important;border-radius:10px!important;box-shadow:none!important;color:#fff}.qa-panel{background:#ef7d20!important}.closing-panel{background:#172235!important}.chat-ticket-summary__officers{display:flex;flex-direction:column;gap:.55rem}.officer-summary-item{padding:.7rem;border:1px solid var(--hd-border);border-radius:9px;background:#fff}.officer-summary-item__top{display:flex;align-items:center;justify-content:space-between;gap:.5rem;color:#28324b;font-size:.78rem}.officer-summary-item__tl{margin-top:.55rem;padding-top:.5rem;border-top:1px solid #eef0f5}.officer-summary-item__tl span{color:var(--hd-muted);font-size:.64rem;font-weight:700}.officer-summary-item__tl p{margin:.15rem 0 0;color:#414b61;font-size:.74rem}.officer-summary-item__attachment{display:flex;align-items:center;gap:.45rem;margin-top:.55rem;padding:.5rem .6rem;border-radius:7px;background:#f0edff;color:var(--hd-primary);font-size:.72rem;font-weight:700;text-decoration:none}.officer-summary-item__attachment span{min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.officer-summary-empty{display:flex;justify-content:center;gap:.5rem;padding:.9rem;color:var(--hd-muted);font-size:.72rem}
    .qa-summary-attachment{display:flex;align-items:center;gap:.4rem;margin-top:.55rem;padding:.45rem .55rem;border-radius:7px;background:rgba(255,255,255,.16);color:#fff;font-size:.7rem;font-weight:700;text-decoration:none}.qa-summary-attachment:hover{background:rgba(255,255,255,.24);color:#fff}.qa-summary-attachment span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
    .followup-chat-card{min-height:0}.followup-chat-card>.card-body{padding:0!important;min-height:0}.followup-chat-card #chat-messages{padding:1rem!important;background:#fbfbfd!important;border-radius:0!important}.chat-controls{padding:.9rem 1rem!important;margin:0!important;background:#fff}.chat-controls .form-control{height:44px!important;border-color:var(--hd-border);font-size:.84rem!important}.chat-controls .chat-icon-button{display:inline-grid!important;place-items:center;width:44px!important;height:44px!important;min-width:44px!important;min-height:44px!important;max-width:44px!important;max-height:44px!important;flex:0 0 44px!important;aspect-ratio:1/1;padding:0!important;margin:0!important;border-radius:9px!important;line-height:1!important;box-sizing:border-box}.chat-controls .chat-icon-button svg{display:block!important;width:18px!important;height:18px!important;min-width:18px!important;min-height:18px!important;max-width:18px!important;max-height:18px!important;aspect-ratio:1/1;flex:none;transform:none}.chat-controls #btn-send{background:var(--hd-primary);border-color:var(--hd-primary)}
    .chat-role-empty{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:.4rem;height:100%;padding:2rem;color:var(--hd-muted);text-align:center}.chat-role-empty>i{width:76px;height:76px;display:grid;place-items:center;margin-bottom:.5rem;border-radius:50%;background:#f0edff;color:var(--hd-primary);font-size:1.8rem}.chat-role-empty strong{color:#20263b;font-size:1rem}.chat-role-empty span{font-size:.78rem}
    @media(min-width:1200px){html,body.followup-role-page{height:100%;overflow:hidden}body.followup-role-page .main-content{height:100vh;margin-top:0!important;overflow:hidden}body.followup-role-page .main-content>.container-fluid.py-4{height:100%;padding:12px!important;overflow:hidden}.followup-page{height:100%;padding:0!important;overflow:hidden}.followup-layout-row{height:100%;margin-top:0;margin-bottom:0;overflow:hidden}.followup-layout-row>.col-xl-8,.followup-layout-row>.col-xl-4{height:100%;min-height:0;overflow:hidden}.followup-main-card{height:100%!important}.followup-main-card>.card-body{display:grid!important;grid-template-rows:minmax(0,1fr) auto;min-height:0;overflow:hidden}#detail-tiket-card,.detail-top-row,.detail-top-row>div{height:100%;min-height:0;margin-bottom:0!important}.detail-top-row{margin-top:0!important}.detail-top-row>div{margin-top:0!important}.detail-ticket-compact{height:100%!important;min-height:0!important}.detail-ticket-compact .flip-card-inner{height:100%;min-height:0!important}.followup-role-action-row{margin:0!important;flex:0 0 auto}.followup-layout-row>.col-xl-4{display:flex;flex-direction:column;gap:1rem!important}.chat-ticket-summary{max-height:42%;min-height:0}.chat-ticket-summary__body{max-height:calc(42vh - 70px)}.followup-chat-card{height:auto!important;min-height:0;flex:1 1 0!important;position:relative!important;top:auto!important}#chat-messages-wrapper{min-height:0;overflow:hidden}}
    @media(max-width:991.98px){.ticket-overview__grid{grid-template-columns:repeat(3,minmax(0,1fr))}}
    @media(max-width:767.98px){.followup-page{padding-inline:.5rem!important}.ticket-overview__grid{grid-template-columns:1fr 1fr}.detail-ticket-compact{height:470px!important;min-height:470px!important}.followup-chat-card{min-height:620px}}
</style>
<script>document.addEventListener('DOMContentLoaded',function(){document.body.classList.add('followup-role-page')});</script>
